SELECT NVL(S.SPEED_HOUR,0) AS SPEED_HOUR 
FROM KPDBA.JOB_DETAIL J 
    ,KPDBA.PRODUCT P
    ,KPDBA.SPEED_GROUP S
WHERE J.PROD_ID = P.PROD_ID
AND J.REVISION = P.REVISION  
AND J.JOB_ID = :JOB_ID
AND S.GROUP_TYPE = DECODE(SUBSTR(:MACH_ID,1,1),6, P.BOX_TYPE,P.PRINT_TYPE)
AND S.MACH_ID = :MACH_ID