SELECT TO_CHAR(START_JOB_TIME,'yyyy-MM-dd HH24:MI:SS') AS START_JOB_TIME
FROM KPDBA.WIP_HEADER A
WHERE SUBSTR(A.TOOLS_ID,1,4) = :AS_MACH_ID
AND A.JOB_ID = :AS_JOB_ID
AND A.BF_FLAG = 'F'
AND A.RUN_REC_STATUS <> 'C'